name: Verificar Vencimentos

on:
  workflow_dispatch:

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar arquivos
        run: |
          pwd
          ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Executar sistema
        run: node index.js
